/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommentFonctionneLePaiementRouteImport } from './routes/comment-fonctionne-le-paiement'
import { Route as DevenirProfesseurRouteImport } from './routes/devenir-professeur'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as MatieresIndexRouteImport } from './routes/matieres.index'
import { Route as MatieresSlugRouteImport } from './routes/matieres.$slug'
import { Route as ProfesseursIndexRouteImport } from './routes/professeurs.index'
import { Route as ProfesseursIdRouteImport } from './routes/professeurs.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminLitigesRouteImport } from './routes/_authenticated/admin.litiges'
import { Route as AuthenticatedAdminOffresRouteImport } from './routes/_authenticated/admin.offres'
import { Route as AuthenticatedAdminProfesseursRouteImport } from './routes/_authenticated/admin.professeurs'
import { Route as AuthenticatedCompteIndexRouteImport } from './routes/_authenticated/compte.index'
import { Route as AuthenticatedCompteCalendrierRouteImport } from './routes/_authenticated/compte.calendrier'
import { Route as AuthenticatedCompteEnfantsRouteImport } from './routes/_authenticated/compte.enfants'
import { Route as AuthenticatedCompteLitigesRouteImport } from './routes/_authenticated/compte.litiges'
import { Route as AuthenticatedCompteReservationsRouteImport } from './routes/_authenticated/compte.reservations'
import { Route as AuthenticatedPaiementBookingIdRouteImport } from './routes/_authenticated/paiement.$bookingId'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProDemandesRouteImport } from './routes/_authenticated/pro.demandes'
import { Route as AuthenticatedProDisponibilitesRouteImport } from './routes/_authenticated/pro.disponibilites'
import { Route as AuthenticatedProMessagesRouteImport } from './routes/_authenticated/pro.messages'
import { Route as AuthenticatedProOffresRouteImport } from './routes/_authenticated/pro.offres'
import { Route as AuthenticatedProProfilRouteImport } from './routes/_authenticated/pro.profil'
import { Route as AuthenticatedProVerificationRouteImport } from './routes/_authenticated/pro.verification'
import { Route as AuthenticatedReserverOfferIdRouteImport } from './routes/_authenticated/reserver.$offerId'
import { Route as ApiPublicBackendConfigRouteImport } from './routes/api/public/backend-config'
import { Route as ApiPublicWebhooksJekoRouteImport } from './routes/api/public/webhooks/jeko'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentFonctionneLePaiementRoute =
  CommentFonctionneLePaiementRouteImport.update({
    id: '/comment-fonctionne-le-paiement',
    path: '/comment-fonctionne-le-paiement',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevenirProfesseurRoute = DevenirProfesseurRouteImport.update({
  id: '/devenir-professeur',
  path: '/devenir-professeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MatieresIndexRoute = MatieresIndexRouteImport.update({
  id: '/matieres/',
  path: '/matieres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresSlugRoute = MatieresSlugRouteImport.update({
  id: '/matieres/$slug',
  path: '/matieres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIndexRoute = ProfesseursIndexRouteImport.update({
  id: '/professeurs/',
  path: '/professeurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIdRoute = ProfesseursIdRouteImport.update({
  id: '/professeurs/$id',
  path: '/professeurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLitigesRoute =
  AuthenticatedAdminLitigesRouteImport.update({
    id: '/admin/litiges',
    path: '/admin/litiges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOffresRoute =
  AuthenticatedAdminOffresRouteImport.update({
    id: '/admin/offres',
    path: '/admin/offres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfesseursRoute =
  AuthenticatedAdminProfesseursRouteImport.update({
    id: '/admin/professeurs',
    path: '/admin/professeurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteIndexRoute =
  AuthenticatedCompteIndexRouteImport.update({
    id: '/compte/',
    path: '/compte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteCalendrierRoute =
  AuthenticatedCompteCalendrierRouteImport.update({
    id: '/compte/calendrier',
    path: '/compte/calendrier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteEnfantsRoute =
  AuthenticatedCompteEnfantsRouteImport.update({
    id: '/compte/enfants',
    path: '/compte/enfants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteLitigesRoute =
  AuthenticatedCompteLitigesRouteImport.update({
    id: '/compte/litiges',
    path: '/compte/litiges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteReservationsRoute =
  AuthenticatedCompteReservationsRouteImport.update({
    id: '/compte/reservations',
    path: '/compte/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaiementBookingIdRoute =
  AuthenticatedPaiementBookingIdRouteImport.update({
    id: '/paiement/$bookingId',
    path: '/paiement/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProDemandesRoute =
  AuthenticatedProDemandesRouteImport.update({
    id: '/pro/demandes',
    path: '/pro/demandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProDisponibilitesRoute =
  AuthenticatedProDisponibilitesRouteImport.update({
    id: '/pro/disponibilites',
    path: '/pro/disponibilites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProMessagesRoute =
  AuthenticatedProMessagesRouteImport.update({
    id: '/pro/messages',
    path: '/pro/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProOffresRoute = AuthenticatedProOffresRouteImport.update({
  id: '/pro/offres',
  path: '/pro/offres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProProfilRoute = AuthenticatedProProfilRouteImport.update({
  id: '/pro/profil',
  path: '/pro/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProVerificationRoute =
  AuthenticatedProVerificationRouteImport.update({
    id: '/pro/verification',
    path: '/pro/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReserverOfferIdRoute =
  AuthenticatedReserverOfferIdRouteImport.update({
    id: '/reserver/$offerId',
    path: '/reserver/$offerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBackendConfigRoute = ApiPublicBackendConfigRouteImport.update({
  id: '/api/public/backend-config',
  path: '/api/public/backend-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksJekoRoute = ApiPublicWebhooksJekoRouteImport.update({
  id: '/api/public/webhooks/jeko',
  path: '/api/public/webhooks/jeko',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comment-fonctionne-le-paiement': typeof CommentFonctionneLePaiementRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres/': typeof MatieresIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/compte/litiges': typeof AuthenticatedCompteLitigesRoute
  '/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/pro/messages': typeof AuthenticatedProMessagesRoute
  '/pro/offres': typeof AuthenticatedProOffresRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/api/public/backend-config': typeof ApiPublicBackendConfigRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/compte/': typeof AuthenticatedCompteIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
  '/api/public/webhooks/jeko': typeof ApiPublicWebhooksJekoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comment-fonctionne-le-paiement': typeof CommentFonctionneLePaiementRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres': typeof MatieresIndexRoute
  '/professeurs': typeof ProfesseursIndexRoute
  '/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/compte/litiges': typeof AuthenticatedCompteLitigesRoute
  '/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/pro/messages': typeof AuthenticatedProMessagesRoute
  '/pro/offres': typeof AuthenticatedProOffresRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/api/public/backend-config': typeof ApiPublicBackendConfigRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/compte': typeof AuthenticatedCompteIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
  '/api/public/webhooks/jeko': typeof ApiPublicWebhooksJekoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comment-fonctionne-le-paiement': typeof CommentFonctionneLePaiementRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres/': typeof MatieresIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/_authenticated/admin/litiges': typeof AuthenticatedAdminLitigesRoute
  '/_authenticated/admin/offres': typeof AuthenticatedAdminOffresRoute
  '/_authenticated/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/_authenticated/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/_authenticated/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/_authenticated/compte/litiges': typeof AuthenticatedCompteLitigesRoute
  '/_authenticated/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/_authenticated/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/_authenticated/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/_authenticated/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/_authenticated/pro/messages': typeof AuthenticatedProMessagesRoute
  '/_authenticated/pro/offres': typeof AuthenticatedProOffresRoute
  '/_authenticated/pro/profil': typeof AuthenticatedProProfilRoute
  '/_authenticated/pro/verification': typeof AuthenticatedProVerificationRoute
  '/_authenticated/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/api/public/backend-config': typeof ApiPublicBackendConfigRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/compte/': typeof AuthenticatedCompteIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
  '/api/public/webhooks/jeko': typeof ApiPublicWebhooksJekoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comment-fonctionne-le-paiement'
    | '/devenir-professeur'
    | '/reset-password'
    | '/accueil'
    | '/messages'
    | '/onboarding'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres/'
    | '/professeurs/'
    | '/admin/litiges'
    | '/admin/offres'
    | '/admin/professeurs'
    | '/compte/calendrier'
    | '/compte/enfants'
    | '/compte/litiges'
    | '/compte/reservations'
    | '/paiement/$bookingId'
    | '/pro/demandes'
    | '/pro/disponibilites'
    | '/pro/messages'
    | '/pro/offres'
    | '/pro/profil'
    | '/pro/verification'
    | '/reserver/$offerId'
    | '/api/public/backend-config'
    | '/admin/'
    | '/compte/'
    | '/pro/'
    | '/api/public/webhooks/jeko'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comment-fonctionne-le-paiement'
    | '/devenir-professeur'
    | '/reset-password'
    | '/accueil'
    | '/messages'
    | '/onboarding'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres'
    | '/professeurs'
    | '/admin/litiges'
    | '/admin/offres'
    | '/admin/professeurs'
    | '/compte/calendrier'
    | '/compte/enfants'
    | '/compte/litiges'
    | '/compte/reservations'
    | '/paiement/$bookingId'
    | '/pro/demandes'
    | '/pro/disponibilites'
    | '/pro/messages'
    | '/pro/offres'
    | '/pro/profil'
    | '/pro/verification'
    | '/reserver/$offerId'
    | '/api/public/backend-config'
    | '/admin'
    | '/compte'
    | '/pro'
    | '/api/public/webhooks/jeko'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comment-fonctionne-le-paiement'
    | '/devenir-professeur'
    | '/reset-password'
    | '/_authenticated/accueil'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres/'
    | '/professeurs/'
    | '/_authenticated/admin/litiges'
    | '/_authenticated/admin/offres'
    | '/_authenticated/admin/professeurs'
    | '/_authenticated/compte/calendrier'
    | '/_authenticated/compte/enfants'
    | '/_authenticated/compte/litiges'
    | '/_authenticated/compte/reservations'
    | '/_authenticated/paiement/$bookingId'
    | '/_authenticated/pro/demandes'
    | '/_authenticated/pro/disponibilites'
    | '/_authenticated/pro/messages'
    | '/_authenticated/pro/offres'
    | '/_authenticated/pro/profil'
    | '/_authenticated/pro/verification'
    | '/_authenticated/reserver/$offerId'
    | '/api/public/backend-config'
    | '/_authenticated/admin/'
    | '/_authenticated/compte/'
    | '/_authenticated/pro/'
    | '/api/public/webhooks/jeko'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommentFonctionneLePaiementRoute: typeof CommentFonctionneLePaiementRoute
  DevenirProfesseurRoute: typeof DevenirProfesseurRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MatieresSlugRoute: typeof MatieresSlugRoute
  ProfesseursIdRoute: typeof ProfesseursIdRoute
  MatieresIndexRoute: typeof MatieresIndexRoute
  ProfesseursIndexRoute: typeof ProfesseursIndexRoute
  ApiPublicBackendConfigRoute: typeof ApiPublicBackendConfigRoute
  ApiPublicWebhooksJekoRoute: typeof ApiPublicWebhooksJekoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-fonctionne-le-paiement': {
      id: '/comment-fonctionne-le-paiement'
      path: '/comment-fonctionne-le-paiement'
      fullPath: '/comment-fonctionne-le-paiement'
      preLoaderRoute: typeof CommentFonctionneLePaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-professeur': {
      id: '/devenir-professeur'
      path: '/devenir-professeur'
      fullPath: '/devenir-professeur'
      preLoaderRoute: typeof DevenirProfesseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/matieres/': {
      id: '/matieres/'
      path: '/matieres'
      fullPath: '/matieres/'
      preLoaderRoute: typeof MatieresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres/$slug': {
      id: '/matieres/$slug'
      path: '/matieres/$slug'
      fullPath: '/matieres/$slug'
      preLoaderRoute: typeof MatieresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/': {
      id: '/professeurs/'
      path: '/professeurs'
      fullPath: '/professeurs/'
      preLoaderRoute: typeof ProfesseursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/$id': {
      id: '/professeurs/$id'
      path: '/professeurs/$id'
      fullPath: '/professeurs/$id'
      preLoaderRoute: typeof ProfesseursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/litiges': {
      id: '/_authenticated/admin/litiges'
      path: '/admin/litiges'
      fullPath: '/admin/litiges'
      preLoaderRoute: typeof AuthenticatedAdminLitigesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offres': {
      id: '/_authenticated/admin/offres'
      path: '/admin/offres'
      fullPath: '/admin/offres'
      preLoaderRoute: typeof AuthenticatedAdminOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/professeurs': {
      id: '/_authenticated/admin/professeurs'
      path: '/admin/professeurs'
      fullPath: '/admin/professeurs'
      preLoaderRoute: typeof AuthenticatedAdminProfesseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/': {
      id: '/_authenticated/compte/'
      path: '/compte'
      fullPath: '/compte/'
      preLoaderRoute: typeof AuthenticatedCompteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/calendrier': {
      id: '/_authenticated/compte/calendrier'
      path: '/compte/calendrier'
      fullPath: '/compte/calendrier'
      preLoaderRoute: typeof AuthenticatedCompteCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/enfants': {
      id: '/_authenticated/compte/enfants'
      path: '/compte/enfants'
      fullPath: '/compte/enfants'
      preLoaderRoute: typeof AuthenticatedCompteEnfantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/litiges': {
      id: '/_authenticated/compte/litiges'
      path: '/compte/litiges'
      fullPath: '/compte/litiges'
      preLoaderRoute: typeof AuthenticatedCompteLitigesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/reservations': {
      id: '/_authenticated/compte/reservations'
      path: '/compte/reservations'
      fullPath: '/compte/reservations'
      preLoaderRoute: typeof AuthenticatedCompteReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiement/$bookingId': {
      id: '/_authenticated/paiement/$bookingId'
      path: '/paiement/$bookingId'
      fullPath: '/paiement/$bookingId'
      preLoaderRoute: typeof AuthenticatedPaiementBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/demandes': {
      id: '/_authenticated/pro/demandes'
      path: '/pro/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof AuthenticatedProDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/disponibilites': {
      id: '/_authenticated/pro/disponibilites'
      path: '/pro/disponibilites'
      fullPath: '/pro/disponibilites'
      preLoaderRoute: typeof AuthenticatedProDisponibilitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/messages': {
      id: '/_authenticated/pro/messages'
      path: '/pro/messages'
      fullPath: '/pro/messages'
      preLoaderRoute: typeof AuthenticatedProMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/offres': {
      id: '/_authenticated/pro/offres'
      path: '/pro/offres'
      fullPath: '/pro/offres'
      preLoaderRoute: typeof AuthenticatedProOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/profil': {
      id: '/_authenticated/pro/profil'
      path: '/pro/profil'
      fullPath: '/pro/profil'
      preLoaderRoute: typeof AuthenticatedProProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/verification': {
      id: '/_authenticated/pro/verification'
      path: '/pro/verification'
      fullPath: '/pro/verification'
      preLoaderRoute: typeof AuthenticatedProVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserver/$offerId': {
      id: '/_authenticated/reserver/$offerId'
      path: '/reserver/$offerId'
      fullPath: '/reserver/$offerId'
      preLoaderRoute: typeof AuthenticatedReserverOfferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/backend-config': {
      id: '/api/public/backend-config'
      path: '/api/public/backend-config'
      fullPath: '/api/public/backend-config'
      preLoaderRoute: typeof ApiPublicBackendConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/jeko': {
      id: '/api/public/webhooks/jeko'
      path: '/api/public/webhooks/jeko'
      fullPath: '/api/public/webhooks/jeko'
      preLoaderRoute: typeof ApiPublicWebhooksJekoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminLitigesRoute: typeof AuthenticatedAdminLitigesRoute
  AuthenticatedAdminOffresRoute: typeof AuthenticatedAdminOffresRoute
  AuthenticatedAdminProfesseursRoute: typeof AuthenticatedAdminProfesseursRoute
  AuthenticatedCompteCalendrierRoute: typeof AuthenticatedCompteCalendrierRoute
  AuthenticatedCompteEnfantsRoute: typeof AuthenticatedCompteEnfantsRoute
  AuthenticatedCompteLitigesRoute: typeof AuthenticatedCompteLitigesRoute
  AuthenticatedCompteReservationsRoute: typeof AuthenticatedCompteReservationsRoute
  AuthenticatedPaiementBookingIdRoute: typeof AuthenticatedPaiementBookingIdRoute
  AuthenticatedProDemandesRoute: typeof AuthenticatedProDemandesRoute
  AuthenticatedProDisponibilitesRoute: typeof AuthenticatedProDisponibilitesRoute
  AuthenticatedProMessagesRoute: typeof AuthenticatedProMessagesRoute
  AuthenticatedProOffresRoute: typeof AuthenticatedProOffresRoute
  AuthenticatedProProfilRoute: typeof AuthenticatedProProfilRoute
  AuthenticatedProVerificationRoute: typeof AuthenticatedProVerificationRoute
  AuthenticatedReserverOfferIdRoute: typeof AuthenticatedReserverOfferIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCompteIndexRoute: typeof AuthenticatedCompteIndexRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminLitigesRoute: AuthenticatedAdminLitigesRoute,
  AuthenticatedAdminOffresRoute: AuthenticatedAdminOffresRoute,
  AuthenticatedAdminProfesseursRoute: AuthenticatedAdminProfesseursRoute,
  AuthenticatedCompteCalendrierRoute: AuthenticatedCompteCalendrierRoute,
  AuthenticatedCompteEnfantsRoute: AuthenticatedCompteEnfantsRoute,
  AuthenticatedCompteLitigesRoute: AuthenticatedCompteLitigesRoute,
  AuthenticatedCompteReservationsRoute: AuthenticatedCompteReservationsRoute,
  AuthenticatedPaiementBookingIdRoute: AuthenticatedPaiementBookingIdRoute,
  AuthenticatedProDemandesRoute: AuthenticatedProDemandesRoute,
  AuthenticatedProDisponibilitesRoute: AuthenticatedProDisponibilitesRoute,
  AuthenticatedProMessagesRoute: AuthenticatedProMessagesRoute,
  AuthenticatedProOffresRoute: AuthenticatedProOffresRoute,
  AuthenticatedProProfilRoute: AuthenticatedProProfilRoute,
  AuthenticatedProVerificationRoute: AuthenticatedProVerificationRoute,
  AuthenticatedReserverOfferIdRoute: AuthenticatedReserverOfferIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCompteIndexRoute: AuthenticatedCompteIndexRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommentFonctionneLePaiementRoute: CommentFonctionneLePaiementRoute,
  DevenirProfesseurRoute: DevenirProfesseurRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MatieresSlugRoute: MatieresSlugRoute,
  ProfesseursIdRoute: ProfesseursIdRoute,
  MatieresIndexRoute: MatieresIndexRoute,
  ProfesseursIndexRoute: ProfesseursIndexRoute,
  ApiPublicBackendConfigRoute: ApiPublicBackendConfigRoute,
  ApiPublicWebhooksJekoRoute: ApiPublicWebhooksJekoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
