/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as MatieresIndexRouteImport } from './routes/matieres.index'
import { Route as MatieresSlugRouteImport } from './routes/matieres.$slug'
import { Route as ProfesseursIndexRouteImport } from './routes/professeurs.index'
import { Route as ProfesseursIdRouteImport } from './routes/professeurs.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminProfesseursRouteImport } from './routes/_authenticated/admin.professeurs'
import { Route as AuthenticatedCompteCalendrierRouteImport } from './routes/_authenticated/compte.calendrier'
import { Route as AuthenticatedCompteEnfantsRouteImport } from './routes/_authenticated/compte.enfants'
import { Route as AuthenticatedCompteReservationsRouteImport } from './routes/_authenticated/compte.reservations'
import { Route as AuthenticatedPaiementBookingIdRouteImport } from './routes/_authenticated/paiement.$bookingId'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProDemandesRouteImport } from './routes/_authenticated/pro.demandes'
import { Route as AuthenticatedProDisponibilitesRouteImport } from './routes/_authenticated/pro.disponibilites'
import { Route as AuthenticatedProOffresRouteImport } from './routes/_authenticated/pro.offres'
import { Route as AuthenticatedProProfilRouteImport } from './routes/_authenticated/pro.profil'
import { Route as AuthenticatedReserverOfferIdRouteImport } from './routes/_authenticated/reserver.$offerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MatieresIndexRoute = MatieresIndexRouteImport.update({
  id: '/matieres/',
  path: '/matieres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresSlugRoute = MatieresSlugRouteImport.update({
  id: '/matieres/$slug',
  path: '/matieres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIndexRoute = ProfesseursIndexRouteImport.update({
  id: '/professeurs/',
  path: '/professeurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIdRoute = ProfesseursIdRouteImport.update({
  id: '/professeurs/$id',
  path: '/professeurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProfesseursRoute =
  AuthenticatedAdminProfesseursRouteImport.update({
    id: '/admin/professeurs',
    path: '/admin/professeurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompteCalendrierRoute =
  AuthenticatedCompteCalendrierRouteImport.update({
    id: '/calendrier',
    path: '/calendrier',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteEnfantsRoute =
  AuthenticatedCompteEnfantsRouteImport.update({
    id: '/enfants',
    path: '/enfants',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteReservationsRoute =
  AuthenticatedCompteReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedPaiementBookingIdRoute =
  AuthenticatedPaiementBookingIdRouteImport.update({
    id: '/paiement/$bookingId',
    path: '/paiement/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProDemandesRoute =
  AuthenticatedProDemandesRouteImport.update({
    id: '/pro/demandes',
    path: '/pro/demandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProDisponibilitesRoute =
  AuthenticatedProDisponibilitesRouteImport.update({
    id: '/pro/disponibilites',
    path: '/pro/disponibilites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProOffresRoute = AuthenticatedProOffresRouteImport.update({
  id: '/pro/offres',
  path: '/pro/offres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProProfilRoute = AuthenticatedProProfilRouteImport.update({
  id: '/pro/profil',
  path: '/pro/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReserverOfferIdRoute =
  AuthenticatedReserverOfferIdRouteImport.update({
    id: '/reserver/$offerId',
    path: '/reserver/$offerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres/': typeof MatieresIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/pro/offres': typeof AuthenticatedProOffresRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres': typeof MatieresIndexRoute
  '/professeurs': typeof ProfesseursIndexRoute
  '/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/pro/offres': typeof AuthenticatedProOffresRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRouteWithChildren
  '/matieres/$slug': typeof MatieresSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/matieres/': typeof MatieresIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/_authenticated/admin/professeurs': typeof AuthenticatedAdminProfesseursRoute
  '/_authenticated/compte/calendrier': typeof AuthenticatedCompteCalendrierRoute
  '/_authenticated/compte/enfants': typeof AuthenticatedCompteEnfantsRoute
  '/_authenticated/compte/reservations': typeof AuthenticatedCompteReservationsRoute
  '/_authenticated/paiement/$bookingId': typeof AuthenticatedPaiementBookingIdRoute
  '/_authenticated/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/_authenticated/pro/disponibilites': typeof AuthenticatedProDisponibilitesRoute
  '/_authenticated/pro/offres': typeof AuthenticatedProOffresRoute
  '/_authenticated/pro/profil': typeof AuthenticatedProProfilRoute
  '/_authenticated/reserver/$offerId': typeof AuthenticatedReserverOfferIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/compte'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres/'
    | '/professeurs/'
    | '/admin/professeurs'
    | '/compte/calendrier'
    | '/compte/enfants'
    | '/compte/reservations'
    | '/paiement/$bookingId'
    | '/pro/demandes'
    | '/pro/disponibilites'
    | '/pro/offres'
    | '/pro/profil'
    | '/reserver/$offerId'
    | '/admin/'
    | '/pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/compte'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres'
    | '/professeurs'
    | '/admin/professeurs'
    | '/compte/calendrier'
    | '/compte/enfants'
    | '/compte/reservations'
    | '/paiement/$bookingId'
    | '/pro/demandes'
    | '/pro/disponibilites'
    | '/pro/offres'
    | '/pro/profil'
    | '/reserver/$offerId'
    | '/admin'
    | '/pro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/compte'
    | '/matieres/$slug'
    | '/professeurs/$id'
    | '/matieres/'
    | '/professeurs/'
    | '/_authenticated/admin/professeurs'
    | '/_authenticated/compte/calendrier'
    | '/_authenticated/compte/enfants'
    | '/_authenticated/compte/reservations'
    | '/_authenticated/paiement/$bookingId'
    | '/_authenticated/pro/demandes'
    | '/_authenticated/pro/disponibilites'
    | '/_authenticated/pro/offres'
    | '/_authenticated/pro/profil'
    | '/_authenticated/reserver/$offerId'
    | '/_authenticated/admin/'
    | '/_authenticated/pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MatieresSlugRoute: typeof MatieresSlugRoute
  ProfesseursIdRoute: typeof ProfesseursIdRoute
  MatieresIndexRoute: typeof MatieresIndexRoute
  ProfesseursIndexRoute: typeof ProfesseursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/matieres/': {
      id: '/matieres/'
      path: '/matieres'
      fullPath: '/matieres/'
      preLoaderRoute: typeof MatieresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres/$slug': {
      id: '/matieres/$slug'
      path: '/matieres/$slug'
      fullPath: '/matieres/$slug'
      preLoaderRoute: typeof MatieresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/': {
      id: '/professeurs/'
      path: '/professeurs'
      fullPath: '/professeurs/'
      preLoaderRoute: typeof ProfesseursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/$id': {
      id: '/professeurs/$id'
      path: '/professeurs/$id'
      fullPath: '/professeurs/$id'
      preLoaderRoute: typeof ProfesseursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/professeurs': {
      id: '/_authenticated/admin/professeurs'
      path: '/admin/professeurs'
      fullPath: '/admin/professeurs'
      preLoaderRoute: typeof AuthenticatedAdminProfesseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte/calendrier': {
      id: '/_authenticated/compte/calendrier'
      path: '/calendrier'
      fullPath: '/compte/calendrier'
      preLoaderRoute: typeof AuthenticatedCompteCalendrierRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/enfants': {
      id: '/_authenticated/compte/enfants'
      path: '/enfants'
      fullPath: '/compte/enfants'
      preLoaderRoute: typeof AuthenticatedCompteEnfantsRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/reservations': {
      id: '/_authenticated/compte/reservations'
      path: '/reservations'
      fullPath: '/compte/reservations'
      preLoaderRoute: typeof AuthenticatedCompteReservationsRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/paiement/$bookingId': {
      id: '/_authenticated/paiement/$bookingId'
      path: '/paiement/$bookingId'
      fullPath: '/paiement/$bookingId'
      preLoaderRoute: typeof AuthenticatedPaiementBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/demandes': {
      id: '/_authenticated/pro/demandes'
      path: '/pro/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof AuthenticatedProDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/disponibilites': {
      id: '/_authenticated/pro/disponibilites'
      path: '/pro/disponibilites'
      fullPath: '/pro/disponibilites'
      preLoaderRoute: typeof AuthenticatedProDisponibilitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/offres': {
      id: '/_authenticated/pro/offres'
      path: '/pro/offres'
      fullPath: '/pro/offres'
      preLoaderRoute: typeof AuthenticatedProOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/profil': {
      id: '/_authenticated/pro/profil'
      path: '/pro/profil'
      fullPath: '/pro/profil'
      preLoaderRoute: typeof AuthenticatedProProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserver/$offerId': {
      id: '/_authenticated/reserver/$offerId'
      path: '/reserver/$offerId'
      fullPath: '/reserver/$offerId'
      preLoaderRoute: typeof AuthenticatedReserverOfferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCompteRouteChildren {
  AuthenticatedCompteCalendrierRoute: typeof AuthenticatedCompteCalendrierRoute
  AuthenticatedCompteEnfantsRoute: typeof AuthenticatedCompteEnfantsRoute
  AuthenticatedCompteReservationsRoute: typeof AuthenticatedCompteReservationsRoute
}

const AuthenticatedCompteRouteChildren: AuthenticatedCompteRouteChildren = {
  AuthenticatedCompteCalendrierRoute: AuthenticatedCompteCalendrierRoute,
  AuthenticatedCompteEnfantsRoute: AuthenticatedCompteEnfantsRoute,
  AuthenticatedCompteReservationsRoute: AuthenticatedCompteReservationsRoute,
}

const AuthenticatedCompteRouteWithChildren =
  AuthenticatedCompteRoute._addFileChildren(AuthenticatedCompteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRouteWithChildren
  AuthenticatedAdminProfesseursRoute: typeof AuthenticatedAdminProfesseursRoute
  AuthenticatedPaiementBookingIdRoute: typeof AuthenticatedPaiementBookingIdRoute
  AuthenticatedProDemandesRoute: typeof AuthenticatedProDemandesRoute
  AuthenticatedProDisponibilitesRoute: typeof AuthenticatedProDisponibilitesRoute
  AuthenticatedProOffresRoute: typeof AuthenticatedProOffresRoute
  AuthenticatedProProfilRoute: typeof AuthenticatedProProfilRoute
  AuthenticatedReserverOfferIdRoute: typeof AuthenticatedReserverOfferIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteRoute: AuthenticatedCompteRouteWithChildren,
  AuthenticatedAdminProfesseursRoute: AuthenticatedAdminProfesseursRoute,
  AuthenticatedPaiementBookingIdRoute: AuthenticatedPaiementBookingIdRoute,
  AuthenticatedProDemandesRoute: AuthenticatedProDemandesRoute,
  AuthenticatedProDisponibilitesRoute: AuthenticatedProDisponibilitesRoute,
  AuthenticatedProOffresRoute: AuthenticatedProOffresRoute,
  AuthenticatedProProfilRoute: AuthenticatedProProfilRoute,
  AuthenticatedReserverOfferIdRoute: AuthenticatedReserverOfferIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MatieresSlugRoute: MatieresSlugRoute,
  ProfesseursIdRoute: ProfesseursIdRoute,
  MatieresIndexRoute: MatieresIndexRoute,
  ProfesseursIndexRoute: ProfesseursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
